// ═══════════════════════════════════════════════════════════════════════
// CODIFICA ARTICOLI — piano dei conti + tabelle caratteristiche + composizione
// Trascrizione dei documenti di Matteo (lug 2026): piano dei conti scansionato
// con appunti a mano (marcati ✎) e tabelle 1–12. Le voci CANCELLATE in rosso
// sui fogli NON sono state trascritte (decisione Nico, 15 lug 2026).
//
// STRUTTURA DEL CODICE — 20 caratteri esatti:
//   [5]  classificazione = 1 famiglia + 2 categoria + 2 caratteristiche
//   [4]  sigla produttore (anagrafica `produttori`)
//   [11] codice articolo del produttore, ZERI DI RIEMPIMENTO PRIMA
//        (padStart: 000LC1D18BD — decisione Nico, 15 lug 2026)
//
// File PURO: solo dati e funzioni, niente DOM, niente Supabase.
// ═══════════════════════════════════════════════════════════════════════

// ── TABELLE CARATTERISTICHE (documento 3) ────────────────────────────────
// Ogni tabella mappa UN carattere → significato. Le tabelle 9 (selettori)
// e 10 (canaline) dei fogli sono descrittive, non a carattere singolo:
// non entrano nella composizione e restano solo sui fogli.
const TABELLE_CODIFICA = {
  1: { nome: 'Tensioni', voci: {
    '0':'0', '1':'12 VDC', '2':'24 VDC', '3':'48 VDC', '4':'110 VDC',
    '5':'230 VDC', '6':'240 VDC', '7':'24–240 VAC ✎',
    '9':'9 V 50-60 Hz', 'A':'12 V 50-60 Hz', 'B':'24 V 50-60 Hz',
    'C':'48 V 50-60 Hz', 'D':'110 V 50-60 Hz', 'E':'230 V 50-60 Hz',
    'F':'240 V 50-60 Hz', 'G':'400 V 50-60 Hz', 'H':'415 V 50-60 Hz',
    'I':'440 V 50-60 Hz', 'J':'500 V 50-60 Hz', 'K':'600 V 50-60 Hz',
    'N':'12 V 60 Hz', 'O':'24 V 60 Hz', 'P':'48 V 60 Hz', 'Q':'110 V 60 Hz',
    'R':'230 V 60 Hz', 'S':'240 V 60 Hz', 'T':'400 V 60 Hz', 'U':'415 V 60 Hz',
    'V':'440 V 60 Hz', 'W':'500 V 60 Hz', 'X':'600 V 60 Hz', 'Z':'Multitensione',
  } },
  2: { nome: 'Correnti di regolazione (A)', voci: {
    '0':'0 — relè con PTC ✎', '1':'0,1–0,16', '2':'0,16–0,25', '3':'0,25–0,4',
    '4':'0,4–0,63', '5':'0,63–1,0', '6':'1–1,6', '7':'1,6–2,5', '8':'2,5–4',
    '9':'4–6,3', 'A':'5,5–8', 'B':'6–10', 'C':'9–14 / 10–16', 'D':'13–18',
    'E':'17–23', 'F':'20–25', 'G':'25–32', 'H':'30–40', 'I':'40–63',
    'J':'60–80', 'K':'80–100', 'L':'90–120', 'M':'vedi anal. N°2006 TMEC ✎',
    'N':'0,15–0,6 ✎ (spec. TMEC)', 'O':'0,35–1,4 ✎ (spec. TMEC)',
    'P':'1,25–5 ✎ (spec. TMEC)', 'Q':'3–12 ✎', 'R':'1,0–13 ✎ (spec. TMEC)',
    'S':'8–32 ✎ (spec. TMEC)', 'T':'6–9 ✎', 'U':'0,55–0,8 ✎', 'V':'0,9–1,25 ✎',
    'W':'1,4–2 ✎',
  } },
  3: { nome: 'Contatti', voci: {
    '0':'0 princ. + 0 ausiliari', '1':'3 princ. + 1 NO', '2':'3 princ. + 1 NC',
    '3':'3 princ. + 1 NO/1 NC', '4':'3 princ.', '5':'4 princ. + 1 NO',
    '6':'4 princ. + 1 NC', '7':'4 princ. + 1 NO/1 NC', '8':'4 princ.',
    '9':'0 princ. + 1 NO', 'A':'libera (✎ 2 NC?)', 'B':'0 princ. + 1 NC',
    'C':'0 princ. + 1 NO + 1 NC', 'D':'0 princ. + 2 NO',
    'E':'0 princ. + 0 NO + 2 NC aux', 'F':'0 princ. + 0 NO + 4 NC aux',
    'G':'0 princ. + 1 NO + 3 NC aux', 'H':'0 princ. + 2 NO + 2 NC aux',
    'I':'0 princ. + 3 NO + 1 NC aux', 'J':'0 princ. + 4 NO + 0 NC aux',
    'K':'0 princ. + 0 NO + 5 NC aux', 'L':'0 princ. + 1 NO + 4 NC aux',
    'M':'0 princ. + 2 NO + 3 NC aux', 'N':'0 princ. + 3 NO + 2 NC aux',
    'O':'0 princ. + 4 NO + 1 NC aux', 'P':'0 princ. + 5 NO + 0 NC aux',
    'Q':'0 princ. + 1 scambio aux', 'R':'0 princ. + 2 scambi aux',
    'S':'0 princ. + 3 scambi aux', 'T':'0 princ. + 4 scambi aux',
  } },
  4: { nome: 'Correnti nominali (A)', voci: {
    '0':'0', 'A':'0,05–0,1', 'B':'0,125–0,5', 'C':'0,8–1,6', 'D':'2–3,15',
    'E':'4', 'F':'5', 'G':'6–6,3', 'H':'8', 'I':'10', 'J':'12–12,5', 'K':'16',
    'L':'20', 'M':'25', 'N':'32', 'O':'40', 'P':'50', 'Q':'63', 'R':'80',
    'S':'100', 'T':'125', 'U':'160', 'V':'200', 'W':'250', 'X':'315',
    'Y':'400', 'Z':'630 + 1000 (✎ 500)',
  } },
  5: { nome: 'Dimensioni (B×h×p)', voci: {
    '0':'0', '!':'80×120×50', '"':'100×100×50', '$':'110×150×70',
    '%':'190×140×90', '&':'190×140×140', '@':'190×240×90',
    '£':'190×240×160 (✎ 220×170×150)', '1':'250×300×150 (✎ 210×150×75)',
    '2':'250×450×150 / 250×600×150 (✎ 254×244×110)', '3':'300×220×120+180',
    '4':'300×300×200', '5':'300×400×150-200-250', '6':'300×500×150+200',
    '7':'300×600×200', '8':'350×450×180',
    '9':'400×500×150+200+250 — 370×1000 zoccolo', 'A':'400×600×200+250',
    'B':'450×350×200 (400×400×200)', 'C':'500×700×200 (✎ 250 — 450×600×210)',
    'D':'500×750×250+310', 'E':'500×1050×350', 'F':'550×1050×350',
    'G':'600×430×220 (✎ 600×600×200)', 'H':'600×800×250+300',
    'I':'600×1000×250', 'J':'600×1000×300', 'K':'600×1200×300',
    'L':'600×1800×500 (✎ 600×370×130 / 600×370×45 / 600×400×120)',
    'M':'700×1200×300+350', 'N':'700×1500×350 (✎ 720×1319×450)',
    'O':'700×1700×350', 'P':'750×500×250 (✎ 760×760×210 (300))',
    'Q':'750×1050×350', 'R':'800×1000×300 + 800×1050×350',
    'S':'800×1200×300 (✎ 400)', 'T':'800×1800×500', 'U':'800×2000×600',
    'V':'900×1050×350 + 1000×600×300', 'W':'1050×350×330',
    'X':'1100×1050×350 (✎ 1000×1350×420)', 'Y':'1200×700×600',
    'Z':'oltre tutto il codice Z',
  } },
  6: { nome: 'Potenza (VA)', voci: {
    '0':'0–2', '1':'3', '2':'4', '3':'5–8', '4':'10–12', '5':'15', '6':'20–25',
    '7':'30–40', '8':'50–70', '9':'75–80', 'A':'100–125', 'B':'150–180',
    'C':'200 (✎ +220)', 'D':'250', 'E':'300–350', 'F':'400', 'G':'500',
    'H':'600–700', 'I':'750', 'J':'800', 'L':'1000–1400',
    'M':'1500–1640 (✎ 1900)', 'N':'2000–2500', 'O':'3000', 'P':'4000',
    'Q':'5000–5200', 'R':'6000', 'S':'7000', 'T':'8000–8500', 'U':'9000',
    'V':'10000', 'W':'15000', 'X':'20000', 'Y':'25000', 'Z':'30000 (✎ +45000)',
  } },
  7: { nome: 'Potenza (kW)', voci: {
    '0':'0', '1':'0,125', '2':'0,15', '3':'0,37', '4':'0,55', '5':'0,75',
    '6':'1,1', '7':'1,5', '8':'2,2', '9':'3', 'A':'4', 'B':'5,5', 'C':'7,5',
    'D':'11', 'E':'15', 'F':'18,5', 'G':'22', 'H':'25', 'I':'30', 'J':'37',
    'K':'45', 'L':'55', 'M':'75', 'N':'90', 'O':'110', 'P':'150', 'Q':'220',
    'R':'250', 'S':'300',
  } },
  8: { nome: 'Sezione cavo', voci: {
    '0':'nessuna', '1':'libero', '2':'0,25 mm² / AWG 20 (✎ AWG 22)',
    '3':'0,35 mm²', '4':'0,50 mm² / AWG 19', '5':'0,75 mm² / AWG 18',
    '6':'1,00 mm² / SWG 17', '7':'1,50 mm² / AWG 14-15-16',
    '8':'2,50 mm² / AWG 12-13', '9':'4,00 mm² / AWG 10-11', 'A':'libero',
    'B':'6,00 mm² / AWG 8-9', 'C':'10,00 mm² / AWG 6-7',
    'D':'16,00 mm² / AWG 4-5', 'E':'25,00 mm² / AWG 3',
    'F':'35,00 mm² / AWG 1-2', 'G':'50,00 mm² / AWG 0',
    'H':'70,00 mm² / AWG 2/0-3/0', 'I':'95,00 mm² / AWG 4/0',
    'J':'120,00 mm² / AWG 5/0', 'K':'150',
  } },
  11: { nome: 'Tolleranza % resistenze C.S.', voci: { '0':'1%', '1':'5%', '2':'10%' } },
  12: { nome: 'Watt resistenze C.S.', voci: {
    '0':'1/4 W', '1':'1/2 W', '2':'1 W', '3':'2 W', '4':'3 W', '5':'4 W', '6':'5 W',
  } },
};

// ── PIANO DEI CONTI (documento 2) ────────────────────────────────────────
// Un GRUPPO per titolo del piano. Ogni voce produce i 4 caratteri dopo la
// famiglia: `cat` (2 char) + `c` (0-2 char fissi) + un carattere per ogni
// tabella in `tabs`. Vincolo: cat.length + c.length + tabs.length === 4.
// Gruppi `libero: true` (schemi non riconducibili a 2+2): input libero di
// 4 caratteri, con lo schema documentato in `note`.
const PIANO_CODIFICA = [
  { fam:'2', nome:'CONTATTORI', alias:'CONTATTO', voci:[
    { cat:'00', c:'', tabs:[1,3], label:'Libero' },
    { cat:'01', c:'', tabs:[1,3], label:'Mini 6A' },
    { cat:'02', c:'', tabs:[1,3], label:'Mini 9A+12A (✎ +16A)' },
    { cat:'03', c:'', tabs:[1,3], label:'Contatt. 9A' },
    { cat:'04', c:'', tabs:[1,3], label:'Contatt. 12A' },
    { cat:'05', c:'', tabs:[1,3], label:'Contatt. 16-18A' },
    { cat:'06', c:'', tabs:[1,3], label:'Contatt. 22-25A' },
    { cat:'07', c:'', tabs:[1,3], label:'Contatt. 32A' },
    { cat:'08', c:'', tabs:[1,3], label:'Contatt. 38-40A' },
    { cat:'09', c:'', tabs:[1,3], label:'Contatt. 50A' },
    { cat:'10', c:'', tabs:[1,3], label:'Contatt. 65A' },
    { cat:'11', c:'', tabs:[1,3], label:'Contatt. 80A' },
    { cat:'12', c:'', tabs:[1,3], label:'Contatt. 95A' },
    { cat:'13', c:'', tabs:[1,3], label:'Contatt. 110/115' },
    { cat:'14', c:'', tabs:[1,3], label:'Contatt. 150A' },
    { cat:'15', c:'', tabs:[1,3], label:'Contatt. 185A' },
    { cat:'16', c:'', tabs:[1,3], label:'Contatt. 220A' },
    { cat:'17', c:'', tabs:[1,3], label:'Contatt. 250A' },
    { cat:'18', c:'', tabs:[1,3], label:'Contatt. 300A' },
    { cat:'19', c:'', tabs:[1,3], label:'Contatt. 350A' },
    { cat:'20', c:'', tabs:[1,3], label:'Contatt. 400A' },
    { cat:'21', c:'', tabs:[1,3], label:'Contatt. 630A' },
    { cat:'22', c:'', tabs:[1,3], label:'Filtro R.C.' },
    { cat:'23', c:'', tabs:[1,3], label:'Libero' },
    { cat:'24', c:'', tabs:[1,3], label:'Contattori modulari' },
    { cat:'25', c:'', tabs:[1,3], label:'Contattori ausiliari' },
  ] },
  { fam:'2', nome:'ACCESSORI PER CONTATTORI', alias:'ACC.CONT', voci:[
    { cat:'26', c:'0', tabs:[1], label:'Bobine' },
    { cat:'26', c:'1', tabs:[3], label:'Contatti aux' },
    { cat:'26', c:'2', tabs:[3], label:'Filtri' },
    { cat:'26', c:'3', tabs:[3], label:'Interblocchi' },
    { cat:'26', c:'4', tabs:[3], label:'Testine-timer' },
    { cat:'26', c:'A', tabs:[3], label:'Accessori' },
  ] },
  { fam:'2', nome:'RELÈ TERMICI', alias:'RELÈ', voci:[
    { cat:'27', c:'0', tabs:[2], label:'Per mini contattori' },
    { cat:'27', c:'1', tabs:[2], label:'GR.1' },
    { cat:'27', c:'2', tabs:[2], label:'GR.2' },
    { cat:'27', c:'3', tabs:[2], label:'GR.3' },
    { cat:'27', c:'4', tabs:[2], label:'GR.4' },
    { cat:'27', c:'5', tabs:[2], label:'GR.5' },
    { cat:'27', c:'6', tabs:[2], label:'GR.6' },
    { cat:'27', c:'7', tabs:[2], label:'Elettronici (PTC) ✎' },
    { cat:'27', c:'A', tabs:[2], label:'Accessori' },
  ] },
  { fam:'2', nome:'INTERRUTTORI AUTOMATICI SCATOLATO', alias:'INTASCAT', voci:[
    { cat:'30', c:'1', tabs:[4], label:'Unipolare' },
    { cat:'30', c:'2', tabs:[4], label:'Bipolare' },
    { cat:'30', c:'3', tabs:[4], label:'Tripolare' },
    { cat:'30', c:'4', tabs:[4], label:'Quadripolare' },
    { cat:'30', c:'5', tabs:[4], label:'Unip.+N' },
    { cat:'30', c:'6', tabs:[4], label:'Trip.+N' },
    { cat:'30', c:'A', tabs:[1], label:'Accessori' },
  ] },
  { fam:'2', nome:'INTERRUTTORI AUTOMATICI MODULARI', alias:'INT.AUTO', voci:[
    { cat:'31', c:'1', tabs:[4], label:'Unipolari' },
    { cat:'31', c:'2', tabs:[4], label:'Bipolari' },
    { cat:'31', c:'3', tabs:[4], label:'Tripolari' },
    { cat:'31', c:'4', tabs:[4], label:'Quadripolari' },
    { cat:'31', c:'5', tabs:[4], label:'Unip.+N' },
    { cat:'31', c:'6', tabs:[4], label:'Trip.+N' },
    { cat:'31', c:'A', tabs:[1], label:'Accessori' },
  ] },
  { fam:'2', nome:'INTERRUTTORI DIFFERENZIALI MODULARI', alias:'INTDMODU', voci:[
    { cat:'32', c:'1', tabs:[4], label:'Unipolari — 0,03 A' },
    { cat:'32', c:'2', tabs:[4], label:'Bipolari — 0,03 A' },
    { cat:'32', c:'3', tabs:[4], label:'Tripolari — 0,03 A' },
    { cat:'32', c:'4', tabs:[4], label:'Quadripolari — 0,03 A' },
    { cat:'32', c:'5', tabs:[4], label:'Unip.+N — 0,03 A' },
    { cat:'32', c:'6', tabs:[4], label:'Trip.+N — 0,03 A' },
    { cat:'32', c:'7', tabs:[4], label:'Libero — 0,03 A' },
    { cat:'32', c:'B', tabs:[4], label:'Unipolari — 0,3 A' },
    { cat:'32', c:'C', tabs:[4], label:'Bipolari — 0,3 A' },
    { cat:'32', c:'D', tabs:[4], label:'Tripolari — 0,3 A' },
    { cat:'32', c:'E', tabs:[4], label:'Quadripolari — 0,3 A' },
    { cat:'32', c:'F', tabs:[4], label:'Unip.+N — 0,3 A' },
    { cat:'32', c:'G', tabs:[4], label:'Trip.+N — 0,3 A' },
    { cat:'32', c:'H', tabs:[4], label:'Libero — 0,3 A' },
    { cat:'32', c:'N', tabs:[4], label:'Unipolari — 0,5 A' },
    { cat:'32', c:'O', tabs:[4], label:'Bipolari — 0,5 A' },
    { cat:'32', c:'P', tabs:[4], label:'Tripolari — 0,5 A' },
    { cat:'32', c:'Q', tabs:[4], label:'Quadripolari — 0,5 A' },
    { cat:'32', c:'R', tabs:[4], label:'Unip.+N — 0,5 A' },
    { cat:'32', c:'S', tabs:[4], label:'Trip.+N — 0,5 A' },
    { cat:'32', c:'T', tabs:[4], label:'Libero — 0,5 A' },
    { cat:'32', c:'A', tabs:[1], label:'Accessori' },
  ] },
  { fam:'2', nome:'INTERRUTTORI CON BOBINA', alias:'INTBOBIN', voci:[
    { cat:'33', c:'', tabs:[1], fisso:'0', label:'Interruttori con bobina (TAB.1 + 0)' },
    { cat:'33', c:'0A', tabs:[], label:'Acc. per interr. con bobina' },
  ] },
  { fam:'2', nome:'INTERRUTTORI AUTOM. MAGNETOTERMICI', alias:'IMAGNETO', voci:[
    { cat:'34', c:'', tabs:[1], fisso:'0', label:'Interr. autom. magnetotermici (TAB.1 + 0)' },
  ] },
  { fam:'2', nome:'SEZIONATORI', alias:'SEZIONAT', voci:[
    { cat:'35', c:'0', tabs:[4], label:'Libero' },
    { cat:'35', c:'1', tabs:[4], label:'Libero (✎ unipolare)' },
    { cat:'35', c:'2', tabs:[4], label:'Bipolare' },
    { cat:'35', c:'3', tabs:[4], label:'Tripolare' },
    { cat:'35', c:'4', tabs:[4], label:'Quadripolare' },
    { cat:'35', c:'5', tabs:[4], label:'Libero' },
    { cat:'35', c:'A', tabs:[4], label:'Accessori per sezionatori' },
  ] },
  { fam:'2', nome:'CASSE METALLO STANDARD', alias:'CASSE ME', voci:[
    { cat:'40', c:'1', tabs:[5], label:'Cassa completa cieca' },
    { cat:'40', c:'2', tabs:[5], label:'Struttura cassa' },
    { cat:'40', c:'3', tabs:[5], label:'Piastra interna' },
    { cat:'40', c:'4', tabs:[5], label:'Porte' },
    { cat:'40', c:'5', tabs:[5], label:'Laterale' },
    { cat:'40', c:'6', tabs:[5], label:'Zoccolo' },
    { cat:'40', c:'7', tabs:[5], label:'Fondo' },
    { cat:'40', c:'8', tabs:[5], label:'Coperchio' },
    { cat:'40', c:'9', tabs:[5], label:'Pulpito completo' },
    { cat:'40', c:'A', tabs:[5], label:'Accessori' },
    { cat:'40', c:'B', tabs:[5], label:'Cassa completa porta vetro' },
    { cat:'40', c:'C', tabs:[5], label:'Cassa completa porta vetro + p.int.' },
    { cat:'40', c:'D', tabs:[5], label:'Anti deflagranti' },
    { cat:'40', c:'AA', tabs:[], label:'Accessori (✎ resist. antic. + cerniere + box chiusura)' },
  ] },
  { fam:'2', nome:'CASSE PLASTICA STANDARD', alias:'CASSE PL', voci:[
    { cat:'41', c:'1', tabs:[5], label:'Cassa completa (✎ + centralini + quadro)' },
    { cat:'41', c:'2', tabs:[5], label:'Struttura cassa' },
    { cat:'41', c:'3', tabs:[5], label:'Piastra interna' },
    { cat:'41', c:'4', tabs:[5], label:'Porte' },
    { cat:'41', c:'5', tabs:[5], label:'Laterale' },
    { cat:'41', c:'6', tabs:[5], label:'Zoccolo' },
    { cat:'41', c:'7', tabs:[5], label:'Fondo' },
    { cat:'41', c:'8', tabs:[5], label:'Coperchio' },
    { cat:'41', c:'A', tabs:[5], label:'Accessori' },
  ] },
  { fam:'2', nome:'ARMADI', alias:'ARMADIO', voci:[
    { cat:'42', c:'1', tabs:[5], label:'Armadio completo' },
    { cat:'42', c:'2', tabs:[5], label:'Struttura cassa' },
    { cat:'42', c:'3', tabs:[5], label:'Piastra interna' },
    { cat:'42', c:'4', tabs:[5], label:'Porte' },
    { cat:'42', c:'5', tabs:[5], label:'Laterale' },
    { cat:'42', c:'6', tabs:[5], label:'Zoccolo' },
    { cat:'42', c:'7', tabs:[5], label:'Fondo' },
    { cat:'42', c:'8', tabs:[5], label:'Coperchio' },
    { cat:'42', c:'9', tabs:[5], label:'Leggio-pulpito' },
    { cat:'42', c:'AA', tabs:[], label:'Accessori' },
  ] },
  { fam:'2', nome:'PORTAFUSIBILI', alias:'P.FUSIBI', voci:[
    { cat:'45', c:'11', tabs:[], label:'Sezionabili — 5×20' },
    { cat:'45', c:'12', tabs:[], label:'Sezionabili — 10×38' },
    { cat:'45', c:'13', tabs:[], label:'Sezionabili — 14×51' },
    { cat:'45', c:'14', tabs:[], label:'Sezionabili — 22×58' },
    { cat:'45', c:'15', tabs:[], label:'Sezionabili — NH 00' },
    { cat:'45', c:'16', tabs:[], label:'Sezionabili — NH 0' },
    { cat:'45', c:'17', tabs:[], label:'Sezionabili — NH 1' },
    { cat:'45', c:'18', tabs:[], label:'Sezionabili — NH 2' },
    { cat:'45', c:'19', tabs:[], label:'Sezionabili — NH 3' },
    { cat:'45', c:'21', tabs:[], label:'Non sezionabili — 5×20' },
    { cat:'45', c:'22', tabs:[], label:'Non sezionabili — 10×38' },
    { cat:'45', c:'23', tabs:[], label:'Non sezionabili — 14×51' },
    { cat:'45', c:'24', tabs:[], label:'Non sezionabili — 22×58' },
    { cat:'45', c:'25', tabs:[], label:'Non sezionabili — NH 00' },
    { cat:'45', c:'26', tabs:[], label:'Non sezionabili — NH 0' },
    { cat:'45', c:'27', tabs:[], label:'Non sezionabili — NH 1' },
    { cat:'45', c:'28', tabs:[], label:'Non sezionabili — NH 2' },
    { cat:'45', c:'29', tabs:[], label:'Non sezionabili — NH 3' },
    { cat:'45', c:'31', tabs:[], label:'Per circuito stampato — 5×20' },
    { cat:'45', c:'32', tabs:[], label:'Per circuito stampato — 10×38' },
    { cat:'45', c:'33', tabs:[], label:'Per circuito stampato — 14×51' },
    { cat:'45', c:'34', tabs:[], label:'Per circuito stampato — 22×58' },
    { cat:'45', c:'35', tabs:[], label:'Per circuito stampato — NH 00' },
    { cat:'45', c:'36', tabs:[], label:'Per circuito stampato — NH 0' },
    { cat:'45', c:'37', tabs:[], label:'Per circuito stampato — NH 1' },
    { cat:'45', c:'38', tabs:[], label:'Per circuito stampato — NH 2' },
    { cat:'45', c:'39', tabs:[], label:'Per circuito stampato — NH 3' },
    { cat:'45', c:'41', tabs:[], label:'Retrop. — 5×20' },
    { cat:'45', c:'42', tabs:[], label:'Retrop. — 10×38' },
    { cat:'45', c:'43', tabs:[], label:'Retrop. — 14×51' },
    { cat:'45', c:'44', tabs:[], label:'Retrop. — 22×58' },
    { cat:'45', c:'45', tabs:[], label:'Retrop. — NH 00' },
    { cat:'45', c:'46', tabs:[], label:'Retrop. — NH 0' },
    { cat:'45', c:'47', tabs:[], label:'Retrop. — NH 1' },
    { cat:'45', c:'48', tabs:[], label:'Retrop. — NH 2' },
    { cat:'45', c:'49', tabs:[], label:'Retrop. — NH 3' },
  ] },
  { fam:'2', nome:'FUSIBILI', alias:'FUSIBILI',
    note:'Sui fogli le serie AM ritardati / GL rapidi / extra rapidi sono CANCELLATE in rosso: non trascritte.',
    voci:[
      { cat:'46', c:'1B', tabs:[], label:'Trazione' },
    ] },
  { fam:'2', nome:'SISTEMI DI RAFFREDDAMENTO', alias:'SIS.RAFF', voci:[
    { cat:'48', c:'00', tabs:[], label:'Libera' },
    { cat:'48', c:'01', tabs:[], label:'Ventola' },
    { cat:'48', c:'02', tabs:[], label:'Filtro' },
    { cat:'48', c:'03', tabs:[], label:'Griglia' },
    { cat:'48', c:'04', tabs:[], label:'Condizionatore' },
    { cat:'48', c:'05', tabs:[], label:'Termostato' },
    { cat:'48', c:'06', tabs:[], label:'Gruppo completo' },
    { cat:'48', c:'07', tabs:[], label:'Sonda temperatura ✎' },
    { cat:'48', c:'70', tabs:[], label:'Accessorio ✎' },
  ] },
  { fam:'2', nome:'INTERRUTTORE SALVAMOTORI MT', alias:'INT.SALV', voci:[
    { cat:'50', c:'1', tabs:[2], label:'GR. 1' },
    { cat:'50', c:'2', tabs:[2], label:'GR. 2' },
    { cat:'50', c:'3', tabs:[2], label:'GR. 3' },
    { cat:'50', c:'4', tabs:[2], label:'Speciali TMEC (Thesys) ✎' },
  ] },
  { fam:'2', nome:'SALVAMOTORI TERMICI', alias:'SALVTERM', voci:[
    { cat:'51', c:'1', tabs:[2], label:'GR. 1 (✎ S00)' },
    { cat:'51', c:'2', tabs:[2], label:'GR. 2 (✎ S0)' },
    { cat:'51', c:'3', tabs:[2], label:'GR. 3 (✎ S2-S3)' },
  ] },
  { fam:'2', nome:'ACCESSORI PER S.MOTORI TERMICI', alias:'ACC.SALV', voci:[
    { cat:'52', c:'1', tabs:[1], label:'Bobina' },
    { cat:'52', c:'2', tabs:[3], label:'Contatti aux' },
    { cat:'52', c:'30', tabs:[], label:'Cassette (3 + vuoto=0)' },
    { cat:'52', c:'40', tabs:[], label:'Varie (4 + vuoto=0)' },
  ] },
  { fam:'2', nome:'TRASFORMATORI', alias:'TRASFORM', voci:[
    { cat:'55', c:'1', tabs:[6], label:'Monofase' },
    { cat:'55', c:'2', tabs:[6], label:'Trifase' },
    { cat:'55', c:'3', tabs:[6], label:'Induttanza monofase' },
  ] },
  { fam:'2', nome:'AUTOTRASFORMATORI', alias:'AUTOTRAS', voci:[
    { cat:'56', c:'1', tabs:[6], label:'Monofase' },
    { cat:'56', c:'2', tabs:[6], label:'Trifase' },
  ] },
  { fam:'2', nome:'IMPEDENZE', alias:'IMPEDEN', voci:[
    { cat:'57', c:'1', tabs:[6], label:'Monofase' },
    { cat:'57', c:'2', tabs:[6], label:'Trifase' },
  ] },
  { fam:'2', nome:'TRASFORMATORI DI MISURA', alias:'TRAS.MIS', voci:[
    { cat:'58', c:'1', tabs:[4], label:'TA' },
    { cat:'58', c:'2', tabs:[1], label:'TV' },
  ] },
  { fam:'2', nome:'MORSETTI', alias:'MORSETTI', voci:[
    { cat:'60', c:'10', tabs:[], label:'Montaggio su guida' },
    { cat:'60', c:'11', tabs:[], label:'Montaggio su guida — morsetto vite' },
    { cat:'60', c:'12', tabs:[], label:'Montaggio su guida — morsetto molla' },
    { cat:'60', c:'13', tabs:[], label:'Montaggio su guida — uso speciale' },
    { cat:'60', c:'20', tabs:[], label:'Montaggio diverso' },
    { cat:'60', c:'21', tabs:[], label:'Montaggio diverso — morsetto vite' },
    { cat:'60', c:'22', tabs:[], label:'Montaggio diverso — morsetto molla' },
    { cat:'60', c:'23', tabs:[], label:'Montaggio diverso — uso speciale' },
  ] },
  { fam:'2', nome:'ACCESSORI PER MORSETTI', alias:'ACC.MORS', voci:[
    { cat:'61', c:'10', tabs:[], label:'Separatori (0 = libera)' },
    { cat:'61', c:'20', tabs:[], label:'Ponti (0 = libera)' },
    { cat:'61', c:'30', tabs:[], label:'Coprimorsetto (0 = libera)' },
    { cat:'61', c:'40', tabs:[], label:'Fermi (0 = libera)' },
    { cat:'61', c:'50', tabs:[], label:'Targhette (0 = libera)' },
  ] },
  { fam:'2', nome:'STRUMENTI DI MISURA, REGOLAZ. E CONTROLLO', alias:'S.REGOLA',
    note:'✎ a mano anche: 9 = contagiri (convert. DA/DC), 10 = switch ethernet — schema da chiarire con Matteo.',
    voci:[
      { cat:'65', c:'1', tabs:[1], label:'Amperometro' },
      { cat:'65', c:'2', tabs:[1], label:'Voltmetro' },
      { cat:'65', c:'3', tabs:[1], label:'Termoregolatore e sonda' },
      { cat:'65', c:'4', tabs:[1], label:'Contaimpulsi' },
      { cat:'65', c:'5', tabs:[1], label:'Relè di controllo e regolazione' },
      { cat:'65', c:'6', tabs:[1], label:'Contaore' },
      { cat:'65', c:'7', tabs:[1], label:'Relè statico' },
      { cat:'65', c:'7A', tabs:[], label:'Accessori per relè statico' },
      { cat:'65', c:'8', tabs:[1], label:'Strum. per controllo e regolazione (✎ velocità)' },
      { cat:'65', c:'9', tabs:[1], label:'Contagiri ✎' },
    ] },
  { fam:'2', nome:'RELÈ ZOCCOLATI', alias:'RELÈ ZO', voci:[
    { cat:'67', c:'', tabs:[1,3], label:'Relè zoccolati (TAB.1 + TAB.3)' },
    { cat:'67', c:'AA', tabs:[], label:'Accessori ✎' },
  ] },
  { fam:'2', nome:'ACCESSORI PER RELÈ ZOCCOLATI', alias:'ACC.RELE', voci:[
    { cat:'68', c:'10', tabs:[], label:'Zoccoli (0 = libera)' },
    { cat:'68', c:'20', tabs:[], label:'Molle (0 = libera)' },
    { cat:'68', c:'30', tabs:[], label:'Contenitori moduli ✎' },
    { cat:'68', c:'50', tabs:[], label:'Accessori ✎' },
  ] },
  { fam:'2', nome:'TEMPORIZZATORI — TIMER', alias:'T.TIMER', voci:[
    { cat:'70', c:'1', tabs:[1], label:'Fix parete' },
    { cat:'70', c:'2', tabs:[1], label:'Fix retropannello (✎ /modulari)' },
  ] },
  { fam:'2', nome:'SENSORI — FINECORSA', alias:'SENSORI',
    note:'5+0: dattiloscritto "SONDE", appunto a mano "ciabatta di distribuzione connettori M8/M12" — da chiarire con Matteo.',
    voci:[
      { cat:'71', c:'1', tabs:[1], label:'Finecorsa' },
      { cat:'71', c:'2', tabs:[1], label:'Sensore ind.' },
      { cat:'71', c:'3', tabs:[1], label:'Sensore capacitivo' },
      { cat:'71', c:'4', tabs:[1], label:'Fotocellula' },
      { cat:'71', c:'50', tabs:[], label:'Sonde (✎ ciabatta distrib. connettori M8/M12)' },
      { cat:'71', c:'6', tabs:[1], label:'Ricevitori/trasmett.' },
      { cat:'71', c:'AA', tabs:[], label:'Accessori (chiavi-rifrang. funi)' },
    ] },
  { fam:'2', nome:'PULSANTERIA', alias:'PULSANT.',
    note:'✎ a mano sul titolo: + portacontatti + contatti.',
    voci:[
      { cat:'75', c:'11', tabs:[], label:'Metallo — diametro 16' },
      { cat:'75', c:'12', tabs:[], label:'Metallo — diametro 22' },
      { cat:'75', c:'13', tabs:[], label:'Metallo — diametro 30 (✎ + portacontatti metallo)' },
      { cat:'75', c:'21', tabs:[], label:'Plastica — diametro 16' },
      { cat:'75', c:'22', tabs:[], label:'Plastica — diametro 22' },
      { cat:'75', c:'23', tabs:[], label:'Plastica — diametro 30 (✎ + contatti + portac. plastica)' },
      { cat:'75', c:'00', tabs:[], label:'Pulsante luminoso da incasso' },
      { cat:'75', c:'24', tabs:[], label:'Chiave per pulsanteria' },
    ] },
  { fam:'2', nome:'ACCESSORI PULSANTI', alias:'ACC.PULS',
    note:'La voce "1+TAB.3 = contatti" è cancellata sui fogli: non trascritta.',
    voci:[
      { cat:'76', c:'2', tabs:[3], label:'Targhette' },
      { cat:'76', c:'3', tabs:[3], label:'Varie' },
      { cat:'76', c:'40', tabs:[], label:'Placche serie civili ✎' },
    ] },
  { fam:'2', nome:'PULSANTIERE — PEDALIERE', alias:'P.PEDALI', voci:[
    { cat:'77', c:'10', tabs:[], label:'Pulsantiera (✎ puls. fungo in cass. — joystick)' },
    { cat:'77', c:'20', tabs:[], label:'Pedaliera' },
  ] },
  { fam:'2', nome:'SPINE — PRESE E CONNETTORI', alias:'SPINE', voci:[
    { cat:'80', c:'10', tabs:[], label:'Prese CEE e spine (✎ connettori multip. ILME)' },
    { cat:'80', c:'20', tabs:[], label:'Tipolari' },
    { cat:'80', c:'30', tabs:[], label:'Elettrovalvole ✎ (dattiloscritto: ovalvole)' },
  ] },
  { fam:'2', nome:'SEGNALATORI', alias:'SEGNALAT', voci:[
    { cat:'82', c:'1', tabs:[1], label:'Lampadine' },
    { cat:'82', c:'2', tabs:[1], label:'Semafori-lampeggianti' },
    { cat:'82', c:'2A', tabs:[], label:'Accessori per semafori-lampeggianti' },
    { cat:'82', c:'3', tabs:[1], label:'Segnalatori acustici' },
    { cat:'82', c:'4', tabs:[1], label:'Bobina' },
    { cat:'82', c:'5', tabs:[1], label:'LED' },
    { cat:'82', c:'5A', tabs:[], label:'Accessori per LED' },
  ] },
  { fam:'2', nome:'COMMUTATORI', alias:'COMMUTAT', voci:[
    { cat:'90', c:'0', tabs:[4], label:'Commutatori (✎ deviatori)' },
    { cat:'90', c:'AA', tabs:[], label:'Accessori (✎ finitura, manovra, protezione)' },
  ] },
  { fam:'2', nome:'SOFT-START', alias:'SOFTSTAR', voci:[
    { cat:'95', c:'', tabs:[1,7], label:'Soft-start (TAB.1 + TAB.7)' },
  ] },
  { fam:'2', nome:'INVERTER', alias:'INVERTER', voci:[
    { cat:'96', c:'', tabs:[1,7], label:'Inverter (TAB.1 + TAB.7)' },
    { cat:'96', c:'0A', tabs:[], label:'Accessori' },
    { cat:'96', c:'0B', tabs:[], label:'Azionamenti ✎' },
  ] },
  { fam:'2', nome:'INVERTER EQUIPAGGIATI', alias:'INVEQUIP', voci:[
    { cat:'97', c:'', tabs:[1,7], label:'Inverter equipaggiati (TAB.1 + TAB.7)' },
  ] },
  { fam:'2', nome:'PLC', alias:'PLC', voci:[
    { cat:'98', c:'00', tabs:[], label:'PLC' },
    { cat:'98', c:'01', tabs:[], label:'Touch ✎' },
  ] },
  { fam:'2', nome:'INVERTER PER MOTORI ASINCRONI', alias:'INV.ASIN', voci:[
    { cat:'99', c:'', tabs:[1,7], label:'Inverter per motori asincroni (TAB.1 + TAB.7)' },
  ] },
  { fam:'3', nome:'PRODOTTI A DISEGNO', alias:'PRODDISE', libero:true,
    note:'Schema progressivo dei fogli: 100 = acquisto (f.te approvv.) · 110 + tipo '
      + '(1 carpenteria, 2 etichette, 3 materiali plastici, 4 pannelli scheda) · '
      + '111 + materiale (1 ferro, 2 alluminio, 3 PVC, 4 acciaio ✎) · 1111 + finitura '
      + '(1 verniciato, 2 zincato, 3 adesivizzato, 4 neutro, 5 goffrati, 6 metallizzati, '
      + '7 anodizzati, 8 stampati). Inserire a mano i 4 caratteri dopo la famiglia.' },
  { fam:'6', nome:'ATTREZZATURE-UTENSILI PER OFFICINA', alias:'UT.OFFIC', voci:[
    { cat:'01', c:'10', tabs:[], label:'Varie' },
    { cat:'01', c:'20', tabs:[], label:'Materiale di consumo' },
    { cat:'01', c:'30', tabs:[], label:'Bancali in abete' },
  ] },
  { fam:'6', nome:'CONTO LAV. ATTR. OFF. PRESSO FORNITORI', alias:'C.LAV.FO', voci:[
    { cat:'02', c:'10', tabs:[], label:'Conto lav. macchinari c.to fornitori' },
  ] },
  { fam:'6', nome:'CANCELLERIA VARIA PER UFFICI', alias:'CANCELLE', voci:[
    { cat:'05', c:'10', tabs:[], label:'Varie' },
  ] },
  { fam:'7', nome:'MATERIALE IN C.TO LAVORO CLIENTI', alias:'C.LAVORO',
    note:'✎ a mano: "Acquisto"; materiale metallico/plastico barrati a penna ma leggibili — trascritti.',
    voci:[
      { cat:'10', c:'00', tabs:[], label:'Materiale metallico' },
      { cat:'20', c:'00', tabs:[], label:'Materiale meccanico' },
      { cat:'30', c:'00', tabs:[], label:'Materiale elettronico' },
      { cat:'40', c:'00', tabs:[], label:'Materiale elettrico (✎ elettromeccanico)' },
      { cat:'50', c:'00', tabs:[], label:'Etichette' },
      { cat:'60', c:'00', tabs:[], label:'Acc. cablaggio' },
      { cat:'70', c:'00', tabs:[], label:'Materiale plastico' },
    ] },
  { fam:'8', nome:'PRESSACAVI PASSO PG', alias:'P.CAVOPG', voci:[
    { cat:'01', c:'11', tabs:[], label:'Met./bianco' },
    { cat:'01', c:'12', tabs:[], label:'Met./grigio' },
    { cat:'01', c:'13', tabs:[], label:'Met./nero' },
    { cat:'01', c:'14', tabs:[], label:'Met./neutro' },
    { cat:'01', c:'21', tabs:[], label:'Plastica/bianca' },
    { cat:'01', c:'22', tabs:[], label:'Plastica/grigia' },
    { cat:'01', c:'23', tabs:[], label:'Plastica/nera' },
    { cat:'01', c:'24', tabs:[], label:'Plastica/neutra' },
    { cat:'01', c:'25', tabs:[], label:'ATEX ✎' },
    { cat:'01', c:'AA', tabs:[], label:'Accessori' },
  ] },
  { fam:'8', nome:'PRESSACAVO PASSO METRICO', alias:'P.CAVIMT',
    note:'✎ a mano compare anche "8.03 pressacavi passo gas" (parzialmente barrato): non trascritto, da chiarire.',
    voci:[
      { cat:'02', c:'11', tabs:[], label:'Met./bianco' },
      { cat:'02', c:'12', tabs:[], label:'Met./grigio' },
      { cat:'02', c:'13', tabs:[], label:'Met./nero' },
      { cat:'02', c:'14', tabs:[], label:'Met./neutro' },
      { cat:'02', c:'21', tabs:[], label:'Plastica/bianca' },
      { cat:'02', c:'22', tabs:[], label:'Plastica/grigia' },
      { cat:'02', c:'23', tabs:[], label:'Plastica/nera' },
      { cat:'02', c:'24', tabs:[], label:'Plastica/neutra' },
      { cat:'02', c:'25', tabs:[], label:'ATEX ✎' },
    ] },
  { fam:'8', nome:'RACCORDI PASSO PG', alias:'RACCPG', voci:[
    { cat:'11', c:'11', tabs:[], label:'Met./bianco' },
    { cat:'11', c:'12', tabs:[], label:'Met./grigio' },
    { cat:'11', c:'13', tabs:[], label:'Met./nero' },
    { cat:'11', c:'14', tabs:[], label:'Met./neutro' },
    { cat:'11', c:'21', tabs:[], label:'Plastica/bianca' },
    { cat:'11', c:'22', tabs:[], label:'Plastica/grigia' },
    { cat:'11', c:'23', tabs:[], label:'Plastica nera' },
    { cat:'11', c:'24', tabs:[], label:'Plastica neutra' },
    { cat:'11', c:'25', tabs:[], label:'Gomma/PVC ✎' },
  ] },
  { fam:'8', nome:'RACCORDI PASSO METRICO', alias:'RACCMT', voci:[
    { cat:'12', c:'11', tabs:[], label:'Met./bianco' },
    { cat:'12', c:'12', tabs:[], label:'Met./grigio' },
    { cat:'12', c:'13', tabs:[], label:'Met./nero' },
    { cat:'12', c:'14', tabs:[], label:'Met./neutro' },
    { cat:'12', c:'21', tabs:[], label:'Plastica/bianca' },
    { cat:'12', c:'22', tabs:[], label:'Plastica/grigia' },
    { cat:'12', c:'23', tabs:[], label:'Plastica/nera' },
    { cat:'12', c:'24', tabs:[], label:'Plastica/neutra' },
  ] },
  { fam:'8', nome:'DADI-TAPPI-RIDUZ. PASSO PG — PASSACAVI', alias:'DADI-PG', voci:[
    { cat:'15', c:'11', tabs:[], label:'Met./bianco' },
    { cat:'15', c:'12', tabs:[], label:'Met./grigio' },
    { cat:'15', c:'13', tabs:[], label:'Met./nero' },
    { cat:'15', c:'14', tabs:[], label:'Met./neutro' },
    { cat:'15', c:'21', tabs:[], label:'Plastica/bianca (✎ tappi × serie civile)' },
    { cat:'15', c:'22', tabs:[], label:'Plastica/grigia' },
    { cat:'15', c:'23', tabs:[], label:'Plastica/nera' },
    { cat:'15', c:'24', tabs:[], label:'Plastica/neutra' },
    { cat:'15', c:'30', tabs:[], label:'Passacavi (✎ gommini)' },
  ] },
  { fam:'8', nome:'DADI-TAPPI-RIDUZIONI PASSO METRICO', alias:'DADI-PM', voci:[
    { cat:'16', c:'00', tabs:[], label:'Met./bianco' },
    { cat:'16', c:'01', tabs:[], label:'Met./grigio' },
    { cat:'16', c:'02', tabs:[], label:'Met./nero' },
    { cat:'16', c:'03', tabs:[], label:'Met./neutro' },
    { cat:'16', c:'21', tabs:[], label:'Plastica/bianca' },
    { cat:'16', c:'22', tabs:[], label:'Plastica/grigia' },
    { cat:'16', c:'23', tabs:[], label:'Plastica/nera' },
    { cat:'16', c:'24', tabs:[], label:'Plastica/neutra' },
    { cat:'16', c:'30', tabs:[], label:'Dado metallo passo gas' },
  ] },
  { fam:'8', nome:'GUAINE', alias:'GUAINE', voci:[
    { cat:'20', c:'10', tabs:[], label:'Metallo/metallo' },
    { cat:'20', c:'11', tabs:[], label:'Metallo/bianco' },
    { cat:'20', c:'12', tabs:[], label:'Metallo/grigio' },
    { cat:'20', c:'13', tabs:[], label:'Metallo/nero' },
    { cat:'20', c:'14', tabs:[], label:'Metallo/neutro' },
    { cat:'20', c:'20', tabs:[], label:'Metallo/gomma' },
    { cat:'20', c:'21', tabs:[], label:'Met.gomma/bianco' },
    { cat:'20', c:'22', tabs:[], label:'Met.gomma/grigio' },
    { cat:'20', c:'23', tabs:[], label:'Met.gomma/nero' },
    { cat:'20', c:'24', tabs:[], label:'Met.gomma/neutro' },
    { cat:'20', c:'30', tabs:[], label:'Plastica' },
    { cat:'20', c:'31', tabs:[], label:'Plastica/bianco' },
    { cat:'20', c:'32', tabs:[], label:'Plastica/grigia' },
    { cat:'20', c:'33', tabs:[], label:'Plastica/nera' },
    { cat:'20', c:'34', tabs:[], label:'Plastica/neutro' },
    { cat:'20', c:'40', tabs:[], label:'Gomma' },
    { cat:'20', c:'41', tabs:[], label:'Gomma/bianca' },
    { cat:'20', c:'42', tabs:[], label:'Gomma/grigia' },
    { cat:'20', c:'43', tabs:[], label:'Gomma/nera' },
    { cat:'20', c:'44', tabs:[], label:'Gomma/neutro' },
    { cat:'20', c:'50', tabs:[], label:'Leggere' },
    { cat:'20', c:'51', tabs:[], label:'Leggere/bianca' },
    { cat:'20', c:'52', tabs:[], label:'Leggere/grigia' },
    { cat:'20', c:'53', tabs:[], label:'Leggera/nera' },
    { cat:'20', c:'54', tabs:[], label:'Leggera/neutra' },
    { cat:'20', c:'60', tabs:[], label:'Antideflagranti' },
    { cat:'20', c:'61', tabs:[], label:'Antideflagranti/bianco' },
    { cat:'20', c:'62', tabs:[], label:'Antideflagranti/grigio' },
    { cat:'20', c:'63', tabs:[], label:'Antideflagranti/nero' },
    { cat:'20', c:'64', tabs:[], label:'Antideflagranti/neutro' },
  ] },
  { fam:'8', nome:'TUBI ✎', alias:'TUBI',
    note:'Solo appunto a mano ("8.21.10 = metallo, 20 = plastica — tubi"): verificare con Matteo.',
    voci:[
      { cat:'21', c:'10', tabs:[], label:'Metallo ✎' },
      { cat:'21', c:'20', tabs:[], label:'Plastica ✎' },
    ] },
  { fam:'8', nome:'FILO / CAVO', alias:'CAVO', voci:[
    { cat:'30', c:'1', tabs:[8], label:'Filo' },
    { cat:'30', c:'2', tabs:[8], label:'Cavo multipolare' },
    { cat:'30', c:'3', tabs:[8], label:'Cavo schermato' },
    { cat:'30', c:'4', tabs:[8], label:'Cavo USB ✎' },
  ] },
  { fam:'8', nome:'FILO / CAVO AWG', alias:'FILOAWG', voci:[
    { cat:'31', c:'1', tabs:[8], label:'Filo' },
    { cat:'31', c:'2', tabs:[8], label:'Cavo multipolare' },
    { cat:'31', c:'3', tabs:[8], label:'Cavo schermato' },
    { cat:'31', c:'40', tabs:[], label:'Fibra ottica / flat ✎' },
  ] },
  { fam:'8', nome:'CAPICORDA', alias:'CAPICORD', voci:[
    { cat:'45', c:'00', tabs:[], label:'Libero' },
  ] },
  { fam:'8', nome:'ACCESSORI PER CABLAGGIO', alias:'ACC.CABL', voci:[
    { cat:'47', c:'00', tabs:[], label:'Cablaggio' },
    { cat:'47', c:'10', tabs:[], label:'Antivibranti (✎ 1Q colonne schermate, 1P barra filettata)' },
    { cat:'47', c:'11', tabs:[], label:'Barra rame' },
    { cat:'47', c:'12', tabs:[], label:'Canalina' },
    { cat:'47', c:'13', tabs:[], label:'Catene' },
    { cat:'47', c:'14', tabs:[], label:'DIN + suprof.' },
    { cat:'47', c:'15', tabs:[], label:'Etichette' },
    { cat:'47', c:'16', tabs:[], label:'Fascette' },
    { cat:'47', c:'17', tabs:[], label:'Guaina treccia (✎ nastro isolante)' },
    { cat:'47', c:'18', tabs:[], label:'Numerini' },
    { cat:'47', c:'19', tabs:[], label:'Segnacavi' },
    { cat:'47', c:'1B', tabs:[], label:'Viteria varia' },
    { cat:'47', c:'1C', tabs:[], label:'Distanziali' },
    { cat:'47', c:'1D', tabs:[], label:'Guaina termorestr.' },
    { cat:'47', c:'1E', tabs:[], label:'Guaina leggera' },
    { cat:'47', c:'1F', tabs:[], label:'Guarnizioni per cassette' },
    { cat:'47', c:'1G', tabs:[], label:'Tondino in gomma' },
    { cat:'47', c:'1H', tabs:[], label:'Cartoni' },
    { cat:'47', c:'1I', tabs:[], label:'Casse legno' },
    { cat:'47', c:'1L', tabs:[], label:'Supporti × guaine / accessori ✎' },
    { cat:'47', c:'1M', tabs:[], label:'Canala metallo ✎' },
    { cat:'47', c:'1N', tabs:[], label:'Ferrite ✎' },
    { cat:'47', c:'1P', tabs:[], label:'Barra filettata ✎' },
    { cat:'47', c:'1Q', tabs:[], label:'Colonne schermate ✎' },
  ] },
  { fam:'A', nome:'CIRCUITO STAMPATO', alias:'C.S.', voci:[
    { cat:'01', c:'11', tabs:[], label:'Singola faccia' },
    { cat:'01', c:'12', tabs:[], label:'Singola faccia con solder' },
    { cat:'01', c:'13', tabs:[], label:'Singola faccia con solder+serigrafia' },
    { cat:'01', c:'21', tabs:[], label:'Doppia faccia' },
    { cat:'01', c:'22', tabs:[], label:'Doppia faccia con solder' },
    { cat:'01', c:'23', tabs:[], label:'Doppia faccia con solder+serigrafia' },
    { cat:'01', c:'00', tabs:[], label:'Spese ✎' },
  ] },
  { fam:'A', nome:'TRASFORMATORI PER ELETTRONICA', alias:'TR.ELETT', voci:[
    { cat:'02', c:'1', tabs:[6], label:'Trasformatori per elettr.' },
  ] },
  { fam:'A', nome:'DISSIPATORI', alias:'DISSIPAT', voci:[
    { cat:'03', c:'00', tabs:[], label:'Dissipatori' },
  ] },
  { fam:'A', nome:'CONTENITORI', alias:'CONTENIT', voci:[
    { cat:'04', c:'01', tabs:[], label:'Pannello' },
    { cat:'04', c:'02', tabs:[], label:'Da piastra' },
    { cat:'04', c:'03', tabs:[], label:'Guida DIN' },
  ] },
  { fam:'A', nome:'BATTERIE', alias:'BATTERIE', voci:[
    { cat:'05', c:'01', tabs:[], label:'Batterie' },
  ] },
  { fam:'A', nome:'POTENZIOMETRI', alias:'POTENZIO', voci:[
    { cat:'10', c:'10', tabs:[], label:'Multigiro' },
    { cat:'10', c:'20', tabs:[], label:'Filo' },
    { cat:'10', c:'A0', tabs:[], label:'Accessori (manopole + tappi + dischi ecc.)' },
  ] },
  { fam:'A', nome:'PONTI DIODI', alias:'PONTEDIO', voci:[
    { cat:'20', c:'00', tabs:[], label:'Faston' },
    { cat:'20', c:'10', tabs:[], label:'C.S.' },
    { cat:'20', c:'30', tabs:[], label:'Diodi' },
  ] },
  { fam:'A', nome:'CONDENSATORI', alias:'CONDENSA', voci:[
    { cat:'25', c:'01', tabs:[], label:'Elett.' },
    { cat:'25', c:'02', tabs:[], label:'Rad.' },
    { cat:'25', c:'03', tabs:[], label:'Rifasam.' },
    { cat:'25', c:'04', tabs:[], label:'Avviamento motori' },
    { cat:'25', c:'A0', tabs:[], label:'Accessori' },
  ] },
  { fam:'A', nome:'INTERRUTTORI (ELETTRONICA)', alias:'INTERR', voci:[
    { cat:'30', c:'10', tabs:[], label:'Leva' },
    { cat:'30', c:'20', tabs:[], label:'Accessori' },
  ] },
  { fam:'A', nome:'CONNETTORI', alias:'CONNETTO', voci:[
    { cat:'32', c:'10', tabs:[], label:'Connettori per C.S.' },
  ] },
  { fam:'A', nome:'FILTRI ANTIDISTURBO', alias:'FILTRANT', voci:[
    { cat:'35', c:'01', tabs:[], label:'Filtro antidisturbo' },
    { cat:'35', c:'02', tabs:[], label:'Scaricatore sovratensioni ✎' },
  ] },
  { fam:'A', nome:'ALIMENTATORI', alias:'ALIMENTA', voci:[
    { cat:'36', c:'01', tabs:[], label:'Alimentatori (✎ trasduttori sul titolo)' },
    { cat:'36', c:'02', tabs:[], label:'UPS o simili ✎' },
    { cat:'36', c:'03', tabs:[], label:'Trasduttori ✎' },
  ] },
  { fam:'A', nome:'PANNELLI OPERATORI', alias:'PANNELLO', voci:[
    { cat:'40', c:'10', tabs:[], label:'Pannello operatore da fornitore' },
  ] },
  { fam:'A', nome:'RESISTENZE PER C.STAMPATO', alias:'RESISTEN', voci:[
    { cat:'50', c:'', tabs:[11,12], label:'Resistenze per circuito stampato (TAB.11 + TAB.12)' },
    { cat:'50', c:'10', tabs:[], label:'Connettori' },
    { cat:'50', c:'20', tabs:[], label:'Varie' },
    { cat:'50', c:'30', tabs:[], label:'Resistenze freno ✎' },
  ] },
  { fam:'A', nome:'CIRCUITI INTEGRATI', alias:'C.INTEGR', voci:[
    { cat:'60', c:'10', tabs:[], label:'Microcontrollore' },
    { cat:'60', c:'20', tabs:[], label:'Sensori' },
  ] },
  { fam:'B', nome:'ASSEMBLAGGIO SCHEDE', alias:'PREMELET', voci:[
    { cat:'0G', c:'05', tabs:[], label:'Assemblaggio scheda elettronica' },
    { cat:'0G', c:'06', tabs:[], label:'Collaudi schede elettroniche' },
    { cat:'0G', c:'07', tabs:[], label:'Accessori varie + cavi + diodi' },
  ] },
  { fam:'C', nome:'SCHEDA FINITA ELETTRONICA', alias:'PROFIELE', voci:[
    { cat:'00', c:'11', tabs:[], label:'Scheda per pompa a giorno' },
    { cat:'01', c:'12', tabs:[], label:'Scheda per pompa con p.schede' },
    { cat:'01', c:'13', tabs:[], label:'Scheda per pompa con contenitore' },
    { cat:'01', c:'14', tabs:[], label:'Assieme per pompa' },
    { cat:'01', c:'11', tabs:[], label:'Scheda per imballaggi a giorno' },
    { cat:'04', c:'11', tabs:[], label:'Assieme per industria tessile' },
    { cat:'04', c:'12', tabs:[], label:'Scheda per tessuti con p.schede' },
    { cat:'04', c:'13', tabs:[], label:'Scheda per i.tessile con contenitore' },
    { cat:'04', c:'14', tabs:[], label:'Assieme per industria tessile' },
    { cat:'05', c:'11', tabs:[], label:'Scheda per industria meccanica' },
    { cat:'05', c:'12', tabs:[], label:'Scheda per industria meccanica' },
    { cat:'05', c:'13', tabs:[], label:'Scheda per i.meccanica con contenitore' },
    { cat:'05', c:'14', tabs:[], label:'Assieme per i.meccanica' },
    { cat:'07', c:'11', tabs:[], label:'Scheda per idrop. aspiratori' },
    { cat:'07', c:'12', tabs:[], label:'Scheda per idrop. aspiratori con p.schede' },
    { cat:'07', c:'13', tabs:[], label:'Scheda per idrop. con contenitore' },
    { cat:'07', c:'14', tabs:[], label:'Assieme per idropul. aspiratori' },
    { cat:'08', c:'11', tabs:[], label:'Scheda per sollevamento' },
    { cat:'08', c:'12', tabs:[], label:'Scheda per sollev. con p.schede' },
    { cat:'08', c:'13', tabs:[], label:'Scheda per sollev. con contenitore' },
    { cat:'08', c:'14', tabs:[], label:'Assieme per sollevamento' },
    { cat:'0C', c:'11', tabs:[], label:'Scheda per vernic. sabb. a giorno' },
    { cat:'0C', c:'12', tabs:[], label:'Scheda vern. sabb. con p.schede' },
    { cat:'0C', c:'13', tabs:[], label:'Scheda vern. sabb. con contenitore' },
    { cat:'0C', c:'14', tabs:[], label:'Assieme per verniciatura sabbiatura' },
    { cat:'0F', c:'01', tabs:[], label:'Scheda Elcose generica' },
    { cat:'0F', c:'11', tabs:[], label:'Scheda generica a giorno' },
    { cat:'0F', c:'12', tabs:[], label:'Scheda generica con p.schede' },
    { cat:'0F', c:'13', tabs:[], label:'Scheda generica con contenitore' },
    { cat:'0F', c:'14', tabs:[], label:'Assieme per generica' },
  ] },
  { fam:'E', nome:'TICKET PER URGENZE VARIE', alias:'TICKET', voci:[
    { cat:'00', c:'11', tabs:[], label:'Ticket per materiali urgenti' },
    { cat:'00', c:'12', tabs:[], label:'Ticket per extra in genere' },
  ] },
];

// ── COMPOSIZIONE ─────────────────────────────────────────────────────────
// blocco5: i 5 caratteri di classificazione già composti dalla UI.
// produttore: sigla di 4 caratteri. codice: codice produttore (max 11),
// riempito con ZERI PRIMA (padStart). Ritorna { ok, codice } o { ok:false, errori }.
function codificaComponi(blocco5, produttore, codice) {
  const errori = [];
  const b5 = String(blocco5 || '').toUpperCase();
  const pr = String(produttore || '').toUpperCase().replace(/\s+/g, '');
  const cod = String(codice || '').toUpperCase().replace(/\s+/g, '');
  if (b5.length !== 5) errori.push('classificazione: servono 5 caratteri (ora ' + b5.length + ')');
  if (pr.length !== 4) errori.push('produttore: servono 4 caratteri (ora ' + pr.length + ')');
  if (cod.length === 0) errori.push('codice produttore: vuoto');
  if (cod.length > 11) errori.push('codice produttore: massimo 11 caratteri (ora ' + cod.length + ')');
  if (errori.length) return { ok: false, errori };
  return { ok: true, codice: b5 + pr + cod.padStart(11, '0') };
}

// Sanity-check dei dati (usato dai test): ogni voce deve produrre ESATTAMENTE
// 4 caratteri dopo la famiglia e riferire tabelle esistenti.
// Ritorna l'elenco dei problemi (vuoto = dati coerenti).
function codificaVerificaDati() {
  const problemi = [];
  PIANO_CODIFICA.forEach(g => {
    if (String(g.fam || '').length !== 1) problemi.push(g.nome + ': famiglia non a 1 carattere');
    if (g.libero) return;
    (g.voci || []).forEach(v => {
      const fissi = (v.cat || '').length + (v.c || '').length + ((v.fisso || '').length);
      const daTab = (v.tabs || []).length;
      if (fissi + daTab !== 4) {
        problemi.push(g.nome + ' / ' + v.label + ': ' + (fissi + daTab) + ' caratteri dopo la famiglia (servono 4)');
      }
      (v.tabs || []).forEach(t => {
        if (!TABELLE_CODIFICA[t]) problemi.push(g.nome + ' / ' + v.label + ': TAB.' + t + ' inesistente');
      });
    });
  });
  return problemi;
}
